### ISSUE TITLE
Publish on Bintray's Maven repository

### ISSUE THREAD

**Issue by coryfklein** [doriordan/skuber#1]
David,

My team would like to use skuber in a project we're building and it would be very helpful if we could download the package via [Bintray's Jcenter/maven repository](https://bintray.com/bintray/jcenter). Looking at JFrog Bintray, it appears that you can link your package by clicking on the "Include My Package" button somewhere.

Is this something you would be open to doing?

Thanks,

Cory

**Comment by doriordan** [comment]
Cory

As it happens I've just recently added support to the build for publishing to bintray - I just haven't actually published a proper release yet...should happen soon, I will update this issue when it is done.

Regards
Dave

**Comment by coryfklein** [comment]
Thanks Dave!

**Comment by doriordan** [comment]
Skuber v1.3.0 has now been released (using "1.3" in the version basically reflects that it supports v1.3 and earlier of Kubernetes). See the README for details.
