### ISSUE TITLE
Support for EC private Keys

### ISSUE THREAD

**Issue by cgbaker** [doriordan/skuber#126]
Docker EE Kubernetes utilizes elliptic curve cryptography, requiring (at least) the ability to parse EC private keys.

I'm adding support this to skuber right now (pull request #127 has a documenting test). There are some arguments in `TLS#getKeyManagers` anticipating different types of private keys, but they're not used. The feedback I'd like is whether to use arguments (which presumably require some hint from the skuber user) or to try to autodetect the key type. Any opinion on this, @doriordan ?

**Comment by cgbaker** [comment]
note, a hint mechanism on `k8sinit` seems sort of gross, so i'm currently working on an automatic approach.

**Comment by cgbaker** [comment]
also, i have no idea what types of keys are within the realm of possibility and should be considered for support. i just know what i need to support in the immediate term.

**Comment by cgbaker** [comment]
some more details: Docker EE is sending out EC private keys as PEM-encoded. the strategy seems to be similar to what is used in Skuber for PCKS#1 encoded RSA private keys; namely, parsing the ASN.1 for EC the private key and generating an ECPrivateKeySpec. I've been working on it for a little while and I'm starting to wish we had a library like BouncyCastle handling this instead. Thoughts?

**Comment by doriordan** [comment]
I would definitely prefer automatically detecting the key type rather than providing some sort of "hint".
At the moment I don't have a specific view on the best way to do it, whether to use BC or some other means - mainly because I don't know enough about what is needed to be done in each case to support EC. I do recall that implementing support for PKCS#1 was fairly painful, and would have been worse if I didn't have some good reference O/S Java code to provide guidance.

**Comment by cgbaker** [comment]
Okay, @doriordan , I've updated skuber to use BC for key parsing. I'm doing some local testing to make sure this is working properly; the testing added to this merge request was fairly trivial.

Their approach is similar to what you went through for PKCS#1... decoding the DER encodings according to the different specs, except that they have support for more than just PKCS#1. I'll update this if the testing works out and remove the `WIP` label from the merge request.

**Comment by doriordan** [comment]
PR #127 has been merged so closing this issue
