### ISSUE TITLE
Default terminationMessagePath is incorrect

### ISSUE THREAD

**Issue by alanbur** [doriordan/skuber#130]
In Container.scala:
>     terminationMessagePath: String = "/var/log/termination",
The default k8s termination path is `/dev/termination-log`. The `terminationMessagePath` parameter to the `Container` constructor should default to the k8s default path, or even better, be made into an `Option()`.

**Comment by alanbur** [comment]
Also, there seems to be no way of setting the `terminationMessagePolicy` for a pod. Valid values are `File` or `FallbackToLogsOnError`.

**Comment by doriordan** [comment]
Good spot @alanbur - I've raised PR#131 to fix the issue
