### ISSUE TITLE
Missing s"..." string interpolator in Watch.scala

### ISSUE THREAD

**Issue by alanbur** [doriordan/skuber#132]
>10:45:35.680 INFO  [ { reqId=7765733c-2d5a-41b2-b69b-8a9b1ceeabe4} } - creating watch on resource $name of kind ${rd.spec.names.kind}]

client/src/main/scala/skuber/api/Watch.scala:39

    context.logInfo(context.logConfig.logRequestBasic, "creating watch on resource $name of kind ${rd.spec.names.kind}")

missing a 's' at the start of the string:

**Comment by doriordan** [comment]
Fixed by PR #136
