### ISSUE TITLE
Getting list resource version from watch events in order to correctly restart watchAll subscription

### ISSUE THREAD

**Issue by chrisbeach** [doriordan/skuber#134]
I’m using a long-lived watchAll subscription to get all pod updates within a namespace. 

If the underlying connection dies, I’d like to restart the watchAll from the latest resourceVersion. 

However, it seems the resourceVersion I get from object.metadata in WatchEvents is not the same kind of version identifier used in the sinceResourceVersion of watchAll queries. 

Is there a way of achieving my dream of a resilient watchAll subscription?

**Comment by doriordan** [comment]
@chrisbeach could you provide a small example with some output showing the resource versions you are seeing?

**Comment by alanbur** [comment]
Note that events are also objects, so the resourceVersion in the event metadata is the resourceVersion for the *event* and *not* the object the event is notifying you has changed. Try object.involvedObject.resourceVersion instead, that might be what you are looking for.

**Comment by alanbur** [comment]
This may be the same issue as #150 __watchAll ignores sinceResourceVersion__

**Comment by doriordan** [comment]
Closing this on assumption above issue resolved, please open another issue if not the case.
