### ISSUE TITLE
Event watches fail after 60 seconds of inactivity

### ISSUE THREAD

**Issue by alanbur** [doriordan/skuber#144]
Event watches are by their very nature long-lived, but at present they fail if there are no event messages within a minute:

> akka.actor.Status$Failure Failure(akka.stream.scaladsl.TcpIdleTimeoutException: TCP idle-timeout encountered on connection to [10.167.120.125:6443], no bytes passed in the last 1 minute)

The default timeout should be infinite, but I'm also not sure how you would override it with the current implementation.

**Comment by alanbur** [comment]
A retry isn't really viable in my case - I need to monitor a long-lived Pod for termination and it could run for two hours or more.

**Comment by doriordan** [comment]
Thanks for the feedback both. I agree Watch default timeout should be infinite - this next on my list to look at...

**Comment by alanbur** [comment]
See https://discuss.lightbend.com/t/akka-http-client-per-request-timeouts/1021 for a discussion about this with the Akka folks.

**Comment by alanbur** [comment]
I tried my suggested solution and it didn't seem to work. I think this will have to be done by using the connection-level API to create a non-cached connection to the K8s server.

**Comment by doriordan** [comment]
This also provides some relevant context: https://github.com/akka/akka-http/issues/1527

I should be able to find some time today/tomorrow to experiment with some changes for this issue.

**Comment by doriordan** [comment]
I merged changes in PR #154 to support this. It works in my testing (just using the Watch example in the examples subproject). So I'm closing this issue, if you encounter problems with the changes please open another issue.

**Comment by rcoh** [comment]
Thanks! Please let me know when you publish a new version

**Comment by opensorceror** [comment]
I'm running into this issue again on v2.4.0, not sure if it is a regression?
