### ISSUE TITLE
Unknown toleration effect 'NoExecute'

### ISSUE THREAD

**Issue by TrevorWatson** [doriordan/skuber#147]
I'm running a build from a clone of the skuber repo and see the following when trying to list pods in a specific namespace:
[INFO] [05/14/2018 13:46:19.771] [main] [skuber.api] [ { reqId=bcb42ba3-da57-4b56-8241-cf6b55539ed6} } - about to send HTTP request: GET https://10.167.120.125:6443/api/v1/namespaces/alan/pods]
[INFO] [05/14/2018 13:46:20.323] [k8sclient-akka.actor.default-dispatcher-3] [skuber.api] [ { reqId=bcb42ba3-da57-4b56-8241-cf6b55539ed6} } - received response with HTTP status 200]
Error listing pods in 'alan' namespace: JsResultException(errors:List((,List(JsonValidationError(List(Unknown toleration effect 'NoExecute'),WrappedArray())))))

I see that the NoSchedule and PreferNoSchedule taints are handled, but not NoExecute. It looks like straightforward changes are required to:

./client/src/main/scala/skuber/json/package.scala
./client/src/main/scala/skuber/Pod.scala
./client/src/test/scala/skuber/json/NodeFormatSpec.scala

I'd offer to fix it but by the time I get the legal team at Oracle to approve a contributor request, we'll all have retired :)

**Comment by doriordan** [comment]
Thanks for raising this issue, fixed by #151
