### ISSUE TITLE
watchAll ignores sinceResourceVersion

### ISSUE THREAD

**Issue by alanbur** [doriordan/skuber#150]
`watchAll` takes an Option parameter `sinceResourceVersion` which allows specification of the starting point from which events are to be delivered. `watchAll` in turn calls `eventsOnKind` which constructs a `maybeResourceVersionQuery` parameter with which to specify the revision, but it isn't passed into the subsequent `context.buildRequest` call, so any specified resource version is ignored.

Looking at the similar `events` method immediately above suggests the call to `context.buildRequest` in `eventsOnKind `should be:

```
val request = context.buildRequest(HttpMethods.GET, rd, None, query = maybeResourceVersionQuery, watch=true)
```

**Comment by doriordan** [comment]
Thanks -definitely a bug, fixed by PR #153
