### ISSUE TITLE
Question: In-cluster authentication

### ISSUE THREAD

**Issue by ngortheone** [doriordan/skuber#169]
Does skuber provide ways to do in-cluster authentication?
Analogous to Go client - they have [in-cluster](https://github.com/kubernetes/client-go/tree/master/examples/in-cluster-client-configuration) and [out-of-cluster](https://github.com/kubernetes/client-go/tree/master/examples/out-of-cluster-client-configuration) authentication methods.

**Comment by ngortheone** [comment]
After spending some time looking at the source code it looks like 
`lazy val useRunningPod: Try[Configuration] ` in `Configuration.scala` should be able to handle "in-cluster" case. 

Unfortunately the documentation does not mention that, so this is a suggestion for improvement

**Comment by ngortheone** [comment]
@doriordan will you be interested in accepting a PR with documentation improvements? If yes, then I will be glad to do some work on this field.

**Comment by doriordan** [comment]
@ngortheone I'd be happy to accept documentation improvements, thanks.

**Comment by Matt-Dee** [comment]
I'd be interested in documentation on this use case
