### ISSUE TITLE
Issue: Flaky ConfigurationSpec test

### ISSUE THREAD

**Issue by ngortheone** [doriordan/skuber#171]
ConfigurationSpec test unpredictably fails once in a while.

```
[error] x Parse EC private keys from kubeconfig file
[error]  Failure(com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'skuber') is not a Success (ConfigurationSpec.scala:157)
[error] x Parse RSA private keys from kubeconfig file
[error]  Failure(com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'skuber') is not a Success (ConfigurationSpec.scala:187)
[error] x Parse PKCS#8 private keys from kubeconfig file
[error]  Failure(com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'skuber') is not a Success (ConfigurationSpec.scala:220)
```

Workaround:
Clean and run tests again. Repeat until succeeds 
```
sbt> clean
sbt> test
```

Java:
```
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

SBT:
```
info] skuber/*:sbtVersion
[info] 	1.0.1
[info] examples/*:sbtVersion
[info] 	1.0.1
[info] root/*:sbtVersion
[info] 	1.0.1
```

**Comment by cgbaker** [comment]
I can confirm this... I saw it while I was developing these tests, it went away while I was trying to fix it, and I mistakenly assumed that I had fixed it. Apparently not...

**Comment by ngortheone** [comment]
@cgbaker do you have ideas why this is happening?

**Comment by cgbaker** [comment]
@ngortheone : i do not. it's a been a few months now and I don't recall the details.

**Comment by doriordan** [comment]
I have never seen this issue running these tests, but based on the error message I imagine this is being raised by
```
 appConfig.checkValid(ConfigFactory.defaultReference(), "skuber")
``` 
at https://github.com/doriordan/skuber/blob/master/client/src/main/scala/skuber/api/package.scala#L775

The default reference configuration at https://github.com/doriordan/skuber/blob/master/client/src/main/resources/reference.conf has the default 'skuber' config preset, so I can only think it is in these cases being overridden by some other application configuration on the classpath.

**Comment by ngortheone** [comment]
Based on my experience happens only if run from sbt. And very likely is a result of
https://github.com/etorreborre/specs2/issues/556

**Comment by ngortheone** [comment]
Downgrading `specs2-core` to `3.8.6` seems to be fixing the problem.
Upgrading to `4.x` should also fix this, but it breaks a lot of tests with errors like

```
[error] .../skuber/client/src/test/scala/skuber/api/ListQueryParamSpec.scala:23:100: could not find implicit value for evidence parameter of type org.specs2.specification.core.AsExecution[ListQueryParamSpec.this.EE => org.specs2.matcher.MatchResult[Any]]
```
I am not familiar with specs2, and my attempt to understand what is `AsExecution` and why it wants implicit `AsExecution[ExecutionEnvironment => MatchResult[Any]` resulted in exploded brain :(

@doriordan not sure whether you prefer to ignore this problem, downgrade or upgrade and fix all tests.

**Comment by doriordan** [comment]
Will have to bite the bullet on updating specs2 at some stage so I'll take a look at that issue (with 4.x) first.

**Comment by doriordan** [comment]
I just tried to rerun the unit tests against specs core `4.0.1` and the only test that failed was the one mentioned above, which is easily fixed by removing the `implicit ee: ExecutionEnv` parameter (a no longer require relic of an older version of the test).
@ngortheone which other tests failed in your environment and how did your run them?

**Comment by ngortheone** [comment]
@doriordan indeed that test was the only broken (I just tried with `specs2-core" % "4.3.2"` ) 
I apologize for misleading information, I must have assumed that that was the first of many.
