### ISSUE TITLE
SSL setup interferes with other libraries also using Akka HTTP

### ISSUE THREAD

**Issue by carstenlenz** [doriordan/skuber#206]
Hi, 

we use Skuber to access our Kubernetes API from inside a pod. Our application also uses other services such as S3 using the Alpakka S3 client that is also Akka HTTP based.

This currently leads to SSL exceptions in the S3 client:
```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

We tracked that down to Skuber overwriting the defaultClientHttpsContext here:
https://github.com/doriordan/skuber/blob/72bed7f4768f8f03709ebc90da6f07b04db5f93e/client/src/main/scala/skuber/api/package.scala#L864

While looking into the code I tried to come up with a change to test if the issue is really caused by this.
In this PR #205 you can look at what I changed in order to get everything back to working (skuber and alpakka s3). Basically I kept the HttpsConnectionContext local and added it to the `requestInvoker` function.

Maybe you can look if a fix of this sort could be integrated somehow?

Thank you :)

**Comment by doriordan** [comment]
It is a valid issue and use case, and at first glance PR #205 looks good to me. I'll have a further look at the PR tomorrow, thanks for raising this.

**Comment by doriordan** [comment]
@carstenlenz I merged your PR and then almost immediately realised that in the case of non TLS connections the modified code sets the connection context to the default SSL context - which will (I think) break non-TLS connections through kubectl proxy.
Rather than revert I'm looking into a fix to basically not set the context explicitly when no `TLS.establishSSLContext` returns None, which was the previous behavior.

**Comment by carstenlenz** [comment]
Hm - the `connectionContext` param of `Http().singleRequest` has a default value setting it to `defaultConnectionPoolSettings` - which is the same value that the modified code set's it to.

the `RequestContext` get's the (unmodified) `sslContext` value.

**Comment by carstenlenz** [comment]
I looked into the `singleRequest` code of Akka - They only use the `connectionContext` when the URI scheme is `https` otherwise `ConnectionContext.noEncryption()` is used. 

Of course not fiddling with the param if not needed might prove more robust in the future :) 

Thanks for your time and effort taking care :)

**Comment by doriordan** [comment]
Yes, I was just reading the same Akka code and as you say it defaults to  `defaultClientHttpsContext` anyway so this PR shouldn't change the behaviour for non-secure endpoints. 

Basically it only uses the context for non-TLS endpoints:
https://github.com/akka/akka-http/blob/master/akka-http core/src/main/scala/akka/http/scaladsl/Http.scala#L828

So all fine, although ideally we wouldn't rely on that default behaviour so in a  future PR I may change it but no urgency.

**Comment by doriordan** [comment]
Closing as #205 has been merged
