### ISSUE TITLE
PersistentVolume.ReclaimPolicy is missing Delete

### ISSUE THREAD

**Issue by cgbaker** [doriordan/skuber#207]
per 
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaim-policy
RelaimPolicy now includes the option for `Delete`. This option is currently missing from `skuber.PersistentVolume.ReclaimPolicy`

**Comment by doriordan** [comment]
@cgbaker are you ok to close this now that https://github.com/doriordan/skuber/pull/208 is merged?

**Comment by cgbaker** [comment]
yes, thanks
