### ISSUE TITLE
getPodLogSource returning 400 when >1 containers

### ISSUE THREAD

**Issue by mike-ruane** [doriordan/skuber#225]
I'm trying to get the logs of a specific container running on a pod. Following the example https://github.com/doriordan/skuber/blob/master/examples/src/main/scala/skuber/examples/podlogs/PodLogsExample.scala, when I try to add `containerName` to the `LogQueryParams` I get a 400 back, telling me a _a container name must be specified_, followed by the possible container names, one of which matches the `containerName` supplied.

Here's the `getPodLogSource`:
```k8s usingNamespace pipelineRun.namespace getPodLogSource (podFut.name, Pod.LogQueryParams(containerName = Some("extractor")))```
Here's the error:
```[extractor-master logs] {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"a container name must be specified for pod extractor-master, choose one of: [extractor paddle]","reason":"BadRequest","code":400}```

Using `kubectl`, I can tail the logs with the following command:
`kubectl logs -f extractor-master -c extractor -n modeltraining` 

Any help would be greatly appreciated.

**Comment by doriordan** [comment]
Looks like a bug [`here`](https://github.com/doriordan/skuber/blob/master/client/src/main/scala/skuber/Pod.scala#L262) - based on the API reference docs the name of the query parameter should be `container` not `containerName`. Sorry about that, I'll create a PR to fix it.

**Comment by mike-ruane** [comment]
Great stuff thank you!
