### ISSUE TITLE
How do we create a job in a particular namespace on the current kubernetes cluster?

### ISSUE THREAD

**Issue by rkadali** [doriordan/skuber#231]
Hi,

I am using Skuber for launching docker instances and jobs on our kubernetes cluster and one thing I noticed is that Skuber is using the namespace based on the configuration initialized. If the configuration specifies a namespace for the context, it is using the namespace otherwise it is defaulting to default namespace. But this doesnt look ideal. Since a context could have multiple namespaces, we need the ability to create a job in a particular namespace given as a parameter. I couldn't find a way to pass a namespace parameter while doing the following snippet of code:

    val cfg = Configuration.parseKubeconfigFile().get
    val k8s = k8sInit(cfg)

    val jobYamlStr = Source.fromFile("./src/main/resources/kubernetes/jobs/datacopy.yaml").mkString
    val jobJsonStr = yamlToJsonString(jobYamlStr)

    var jobJSObject = Json.parse(jobJsonStr)

    val job = Json.parse(jobJsonStr).as[Job](skuber.json.batch.format.jobFormat)

    val existingTemplateSpec: Pod.Spec = job.copySpec.template.flatMap(_.spec).getOrElse(Pod.Spec())
    val updatedJob = job.withTemplate(
      Pod.Template.Spec(
        spec = Some(
          existingTemplateSpec.copy(
            containers = existingTemplateSpec.containers.headOption.map(
              container => container.copy(
                env = container.env :+ EnvVar(name = "ARTIFACT_TYPE", value = EnvVar.strToValue(serviceInstanceType))
                                    :+ EnvVar(name = "WORKFLOW_NAME", value = EnvVar.strToValue(workflowName))
                                    :+ EnvVar(name = "RUN_ID", value = EnvVar.strToValue(runId))
                                    :+ EnvVar(name = "ARTIFACT_PATH_LIST", value = EnvVar.strToValue(artifactList))
             )
            ).toList
          )
        )
      )
    )

    implicit val fmt = skuber.json.batch.format.jobFormat
    val jobRequest = k8s.create[Job](updatedJob)

Can someone please clarify if Skuber client supports the ability to create a job on a particular namespace given as a parameter? If so, can you give me some sample?

**Comment by doriordan** [comment]
Since #211  was merged you can specify explicitly the namespace in the metadata of the object you are creating, and that takes precedence over the configuration (you will need to be using v2.0.11).
We do need to update the docs for this, in the meantime the test at https://github.com/doriordan/skuber/blob/master/client/src/it/scala/skuber/NamespaceSpec.scala gives an example of how to do this for a Pod, and you should be able to do something very similar with a Job.

**Comment by rkadali** [comment]
Thank you for the resolution.
