### ISSUE TITLE
Creating custom resource object from yml

### ISSUE THREAD

**Issue by ashishkoho** [doriordan/skuber#245]
For a new resource, for example,
`apiVersion: argoproj.io/v1alpha1
kind: Workflow                  #new type of k8s spec
metadata:
  generateName: hello-world-    #name of workflow spec
spec:
  entrypoint: whalesay          #invoke the whalesay template
  templates:
  - name: whalesay              #name of template
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
      resources:                #don't use too much resources
        limits:
          memory: 32Mi
          cpu: 100m`
Considering that CRDs has already been created. How to create this object above using the library?
Is there a better way to load the YAML and create it?

**Comment by doriordan** [comment]
The documentation at https://github.com/doriordan/skuber/blob/master/docs/GUIDE.md#json-mapping gives an example of loading a resource from Json or Yaml. The same approach should work just fine with a custom resource, something like:
```
val workflow = Json.parse(workflowJsonStr).as[Workflow]
```
The above assumes you have defined a `Workflow` type for your CRD with implicit Json formatter and resource definition, using for example a similar approach as in that used for `TestResource` at https://github.com/doriordan/skuber/blob/6f2f17d92c6eac376579b311b055f9a7d21caad0/client/src/it/scala/skuber/CustomResourceSpec.scala#L45

**Comment by doriordan** [comment]
Closing as answered
