### ISSUE TITLE
Job support

### ISSUE THREAD

**Issue by ndeslandes** [doriordan/skuber#25]
When do you plan to add support for Jobs?
Thanks

**Comment by doriordan** [comment]
Hi. Jobs are already supported on master branch - see https://github.com/doriordan/skuber/pull/14. Not yet supported in a release as the last release (1.3) was some time ago (I'm planning a release to support Kubernetes 1.5 / 1.4 within weeks which will include jobs and everything else currently on master, as well as some other features.)
