### ISSUE TITLE
The list() method with config maps exceeds Akka max entity size

### ISSUE THREAD

**Issue by sathibault** [doriordan/skuber#254]
Since the list method returns the entire content of the objects, it can result in a very large result for config maps that can be arbitrarily large.  Is there any way to fetch the names of config maps without their actual content?

**Comment by doriordan** [comment]
At the moment there isn't a clean way to do this with skuber - the nearest you can get would probably be to use the `limit` and `continue` flags in `ListOptions` passed to a series of `listWithOptions` call to basically retrieve the resources in a paged manner (see https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks for hos this works from a Kubernetes perspective). 
What would probably be better for your use use case is support for the relatively new Kubernetes API feature that allows resource lists to be returned in tabular format (see https://kubernetes.io/docs/reference/using-api/api-concepts/#receiving-resources-as-tables). I've raised issue #257 to track adding support to skuber for this.

**Comment by sathibault** [comment]
Okay, thanks
