### ISSUE TITLE
Play 2.7 support

### ISSUE THREAD

**Issue by alexis2b** [doriordan/skuber#256]
Using skuber 2.1.0 in a Play 2.7 project I get what looks like a binary incompatibility introduced by a change in play-json:
``Caused by: java.lang.NoSuchMethodError: play.api.libs.json.Reads$.traversableReads(Lscala/collection/generic/CanBuildFrom;Lplay/api/libs/json/Reads;)Lplay/api/libs/json/Reads;
        at skuber.json.format.package$.<init>(package.scala:100)
        at skuber.json.format.package$.<clinit>(package.scala)
        at domain.batch.KubernetesService$.debugListPods(KubernetesService.scala:17)``

This looks similar to what other packages have experienced (cf. https://github.com/ReactiveMongo/Play-ReactiveMongo/issues/267).

Thanks a lot for all the hard work on skuber, cheers!

**Comment by jeffrey-aguilera** [comment]
I have a PR that fixes this: https://github.com/doriordan/skuber/pull/255

**Comment by doriordan** [comment]
Thanks @alexis2b and @jeffrey-aguilera - I'll take a closer look at #255

**Comment by olivierlemasle** [comment]
PR #255 has been closed by its author :-(

**Comment by olivierlemasle** [comment]
I've finally created a new PR to fix this issue: #263.

**Comment by jeffrey-aguilera** [comment]
> PR #255 has been closed by its author :-(

No, I did not close that PR.
