### ISSUE TITLE
ClassCastException when reading GCP configured auth provider config

### ISSUE THREAD

**Issue by jroper** [doriordan/skuber#267]
I get the following exception:

```
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Date
	at skuber.api.Configuration$.authProviderRead$1(Configuration.scala:162)
	at skuber.api.Configuration$.toK8SAuthInfo$1(Configuration.scala:172)
	at skuber.api.Configuration$.$anonfun$parseKubeconfigStream$7(Configuration.scala:192)
	at skuber.api.Configuration$.$anonfun$parseKubeconfigStream$4(Configuration.scala:137)
```

When reading a GKE auth provider config that has been written by the gcloud command. Here's the config that command wrote:

```yaml
- name: gke_my-project_us-central1-a_my-cluster
  user:
    auth-provider:
      config:
        access-token: ####
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
        expiry: "2019-04-18T03:43:23Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

The problem appears to be that it's writing the `expiry` field as a String, but Skuber is expecting it to be a YAML date. I've got no idea if skuber is right or gcloud is right, but perhaps its safer to read as a string and parse manually?

**Comment by jroper** [comment]
This is actually really frustrating because I can update the configuration file manually, but every time I use `kubectl` it writes reverts my changes. Here's the go client code that reads and writes this file, it seems to treat the whole config file as if it were JSON, and only deals with strings:

https://github.com/kubernetes/client-go/blob/ee7a1ba5cdf1292b67a1fdf1fa28f90d2a7b0084/plugin/pkg/client/auth/gcp/gcp.go#L81

Furthermore, it appears that the format of the string can be completely customised:

https://github.com/kubernetes/client-go/blob/ee7a1ba5cdf1292b67a1fdf1fa28f90d2a7b0084/plugin/pkg/client/auth/gcp/gcp.go#L104-L106

That of course is not compatible with YAML dates, so it must be treated as a String to support that feature.

So I will submit a pull request to make Skuber do the same.

**Comment by edio** [comment]
A gentle bump. Any plans to fix this by merging the proposed PR?

**Comment by jroper** [comment]
I've published a build of this PR to my bintray account as a workaround, sbt settings:

```scala
resolvers += Resolver.bintrayRepo("jroper", "maven")
libraryDependencies += "io.skuber" %% "skuber" % "2.2.0-jroper-1"
```
