### ISSUE TITLE
Typo in podManagementPolicy - apps.v1.StatefulSet

### ISSUE THREAD

**Issue by AldusLorde** [doriordan/skuber#276]
![image](https://user-images.githubusercontent.com/34024120/58714688-eaa92a00-83cd-11e9-86d3-89cb322b4a0b.png)

![image](https://user-images.githubusercontent.com/34024120/58714753-14625100-83ce-11e9-8f06-8d58723dc169.png)

Skuber generates wrong property so it's not recognized.

**Comment by AldusLorde** [comment]
You accepted my pull request, so could you release a minor version, please?

**Comment by doriordan** [comment]
Version 2.3.0 has this change (apologies for delay)
