### ISSUE TITLE
Is there a debug mode to see the Json or Yaml that is sent to the K8S API?

### ISSUE THREAD

**Issue by NicolasRouquette** [doriordan/skuber#278]
I would like to see the resources sent to the K8S api in Yaml form.

Is this possible?

Currently, with `skuber.api` logging enabled at the `DEBUG` level and with the following system properties`-Dskuber.log.request.object.full=true -Dskuber.log.response.object.full=true`, the closest is the representation of the Skuber scala case resources before it's marshaled and sent to K8s. I would like to see the marshaled representation in Yaml, as if one were to use `kubectl apply -f -` to send this info.

**Comment by doriordan** [comment]
There isn't built in support for logging Yaml representations of object resources in Skuber at the moment. 
One way to support it in an application could be to wrap your calls to the Skuber API with code that converts the passed object resources to Json (using the Skuber provided implicit json formatters that get passed to the API) then parse the Json representations using an off the shelf library (e.g. SnakeYaml) that supports dumping back out in Yaml format.

**Comment by MPV** [comment]
Sounds promising!

Please excuse my early learning efforts — still getting familiar with the Scala ecosystem...

Anyone that would be open to sharing some concrete examples/suggestions on how one might do this?

I'm trying to get acquainted with the json formatters, but I've yet figured out how to make use of them to convert into Json representations: https://github.com/doriordan/skuber/blob/master/client/src/main/scala/skuber/json/package.scala

For example, I'd like to convert a [`Service`](https://github.com/doriordan/skuber/blob/master/client/src/main/scala/skuber/Service.scala) that I've created using skuber, into a YAML/JSON representation (that I can compare with other files on disk).
