### ISSUE TITLE
HasStatusSubresource isn't implemented

### ISSUE THREAD

**Issue by AldusLorde** [doriordan/skuber#282]
Hi) I came across that trait HasStatusSubresource isn't implemented by any ObjectResource so getStatus method doesn't work. It leads to code duplicates because of a similarity of status objects which aren't connected.

**Comment by doriordan** [comment]
Hi @AldusLorde  - the  API methods for accessing the status are intended for use with custom resources, and will only work if the associated custom resource definition has enabled status subresources (see https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#status-subresource)
The `HasStatusResource[T]` is simply intended as a means for the implementor of the client-side support for a given custom resource type T to ensure that the status methods on the client side can only be called if there is an implicit object of that type available which the implementation  should provide if status subresources are supported, and can do very easily - see https://github.com/doriordan/skuber/blob/master/client/src/main/scala/skuber/CustomResource.scala#L51 for one way to do it.
