### ISSUE TITLE
Release for Scala 2.13

### ISSUE THREAD

**Issue by runtologist** [doriordan/skuber#295]
Thanks for this awesome library! How about cutting a release supporting Scala 2.13, now that it is supported in master?

**Comment by Executioner1939** [comment]
Are we going to get a version for 2.13 published?

**Comment by psisoyev-ltq** [comment]
any updates here?

**Comment by psisoyev** [comment]
any updates here? any help needed?

**Comment by runtologist** [comment]
❤️

**Comment by Executioner1939** [comment]
As a workaround I have published this to our companies private Nexus Repo, this doesn't help anyone else obviously but might help convey urgency.

**Comment by Vlad1Badilovskii** [comment]
![image](https://user-images.githubusercontent.com/43775994/71110060-389d4800-21cf-11ea-87ab-8bb530ed6db9.png)
thx for 2.13 support

**Comment by doriordan** [comment]
Closing as Scale 2.13 supported now in v2.4.0
