### ISSUE TITLE
Cancelling running request?

### ISSUE THREAD

**Issue by edio** [doriordan/skuber#298]
Is there a way to cancel already running request in skuber?

I do not have experience with Akka, maybe there's a straightforward solution assumming you know how Akka operates.

**Comment by doriordan** [comment]
It is not possible, there is no support on the server-side (Kubernetes) for cancelling outstanding requests, nor any way to cancel the Futures returned by the skuber API on the client-side. This blog post gives some explanation as to why Futures in Scala generally are not cancellable: https://viktorklang.com/blog/Futures-in-Scala-protips-6.html.

**Comment by edio** [comment]
Got it. Thanks for the explanation
