### ISSUE TITLE
JSON deserialization error when no Tls secretName is defined for Ingress spec

### ISSUE THREAD

**Issue by avareljian** [doriordan/skuber#303]
Field `secretName` in `Ingress.TLS` should be optional, to reflect this [documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#ingresstls-v1beta1-extensions):

> Field is left optional to allow SSL routing based on SNI hostname alone.

`secretName` is currently required by this Scala client, which results in this JSON deserialization error:
```
akka.http.scaladsl.server.RejectionError: ValidationRejection({"obj.items[0].spec.tls[0].secretName":[{"msg":["error.path.missing"],"args":[]}]},Some(skuber.json.PlayJsonSupportForAkkaHttp$PlayJsonError: 
{"obj.items[0].spec.tls[0].secretName":[{"msg":["error.path.missing"],"args":[]}]}))
```

**Comment by doriordan** [comment]
Closing as fixed by https://github.com/doriordan/skuber/pull/309 - thanks for raising the issue
