### ISSUE TITLE
Using startupProbes

### ISSUE THREAD

**Issue by jethrogillgren** [doriordan/skuber#304]
Is there a way to use a [startupProbe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes)  in Skuber?

Thanks

**Comment by doriordan** [comment]
Not at the moment, it is a fairly new Kubernetes feature (introduced as alpha in 1.16). Looks easy to add support though, should be able to get it into next release of Skuber
