### ISSUE TITLE
Failing to parse DaemonSet JSON because Status is missing Conditions list

### ISSUE THREAD

**Issue by mzeljkovic** [doriordan/skuber#305]
##Description

When trying to parse DaemonSet from JSON Skuber is expecting a conditions list which isn't supplied by the api server

```JsError(List((/status/conditions,List(JsonValidationError(List(error.path.missing),WrappedArray())))))```

It seems that Conditions list isn't an Option

**Comment by doriordan** [comment]
Closing this as fixed by #306
