### ISSUE TITLE
Capability to undo changes done to a deployment

### ISSUE THREAD

**Issue by dinoopt** [doriordan/skuber#308]
When I patch a deployment using the `patch` API and later the pod doesn't come up due to some reason, I want to undo the changes done to the deployment using an equivalent of 
```
kubectl rollout undo deployment.v1.apps/nginx-deployment
```
I couldn't find a matching skuber API to undo the changes done to the deployment. Could you please let know if there is a way to do this in skuber ?

**Comment by doriordan** [comment]
There isn't a way currently in skuber to do this. Deployments keep a history which could be used to implement such a feature, but looks like there is a still a fair bit of client-side logic needed to implement it (see https://github.com/kubernetes/kubernetes/blob/1d365a8cad4e4d578d613b5f5ff896bd0c3a8bfa/pkg/controller/deployment/rollback.go#L34)

**Comment by doriordan** [comment]
Actually above is the logic in the deployment controller, how that should be controlled from client in latest version of Kubernetes isn't immediately clear to me - there is a DeploymentRollback type that looks like it could be used but it seems to be deprecated (https://github.com/kubernetes/api/blob/master/extensions/v1beta1/types.go#L160).

**Comment by doriordan** [comment]
So on a little further investigation, it looks like the kubectl client code for rolling back deployments looks at the historic replicasets associated with previous revisions of the deployment (normally 10 revisions are kept but that can be changed) and then copies the template from the desired revision into the deployment, which effectively rolls back to that revision.
This is logic that probably could be built on top of existing skuber library by a client.
