### ISSUE TITLE
Upgrade to the latest Akka & Akka HTTP

### ISSUE THREAD

**Issue by michael-read** [doriordan/skuber#313]
I would like to offer to upgrade to Akka (2.6.8) & Akka HTTP (10.1.12) to latest. However, this would end support for Scala 2.11 since latest Akka no longer supports it.

**Comment by michael-read** [comment]
Please see https://github.com/doriordan/skuber/pull/314

**Comment by doriordan** [comment]
Latest release updated the stack so closing this
