### ISSUE TITLE
LoggingConfig not referring to actual system property

### ISSUE THREAD

**Issue by hagaiovadia** [doriordan/skuber#319]
skuber logs are quite noisy. 
I wanted to disable some of the logs and found `LoggingConfig.scala` in order to config the logs.
The problem is that you can see from the source code that LoggingConfig not taking the actual system property, it's turns everything to true.

LoggingConfig.scala
https://github.com/doriordan/skuber/blob/0982ac699a9a85e9f317eb7ee1f7ddbb08828c98/client/src/main/scala/skuber/api/client/LoggingConfig.scala

`sysProps.get(s"skuber.log.$logEventType").map(_ => true).getOrElse(fallback)`
This line means that "if the system property exists" -> turn it into "true" no matter what the value is.
The fix should be:
`sysProps.get(s"skuber.log.$logEventType").map(value => value.toBoolean).getOrElse(fallback)`

How to reproduce?
1. Run the client with java argument:
-Dskuber.log.request=false
2. Make a simple get API request to skuber client
3. You keep see logs like the following
```[INFO] [09/10/2020 10:27:26.655] [sonic-actor-system-akka.actor.default-dispatcher-16] [skuber.api] [ { reqId=a5ea32ee-d0f3-44a2-bd7e-d2953c5c4d25} } - received response with HTTP status 200]```

**Comment by hagay3** [comment]
@doriordan 
fixed and tested.
please merge, thanks 
https://github.com/doriordan/skuber/pull/320

**Comment by grcanosa-alstom** [comment]
Does anyone know how to turn off the logs?

**Comment by hagaiovadia** [comment]
Hi @grcanosa-alstom , this PR already merged to the new fork of this library.
https://github.com/hagay3/skuber

If you wish to disable all the logs except errors you can try this:
```akka.loglevel = "ERROR"```
In case you want to disable specific logs you can now use the new client I released with the above fix.

for example:
```skuber.log.logRequestBasic=false```

**Comment by doriordan** [comment]
Fix was merged, thanks
