### ISSUE TITLE
DaemonSet Question

### ISSUE THREAD

**Issue by Matt-Dee** [doriordan/skuber#326]
Any plans on implementing DaemonSet functionality?

**Comment by hagaiovadia** [comment]
This repo seems to have been abandoned.
A maintained fork is available here
https://github.com/hagay3/skuber
Please open the issue in the new repo in order to address the issue.
Thanks,
Hagai

**Comment by doriordan** [comment]
DaemonSet has long been implemented, see https://github.com/doriordan/skuber/blob/master/client/src/main/scala/skuber/apps/v1/DaemonSet.scala
