### ISSUE TITLE
update akka and akka http version to the latest

### ISSUE THREAD

**Issue by frankdvd** [doriordan/skuber#329]
Is that possible to update the Akka and Akka HTTP version to the latest version?

Akka: 2.6.10
Akka HTTP: 10.2.2 

Thank you!

**Comment by hagaiovadia** [comment]
This repo seems to have been abandoned.
A maintained fork is available here
https://github.com/hagay3/skuber
Akka HTTP is already updated to the latest version in the above fork.
Thanks,
Hagai
