### ISSUE TITLE
InvalidKeyException in skuber 2.6.4

### ISSUE THREAD

**Issue by dswiecki** [doriordan/skuber#340]
Trying to connect to cluster results in 
```
An exception or error caused a run to abort: java.security.InvalidKeyException: IOException : version mismatch: (supported:     00, parsed:     01

**Comment by hagay3** [comment]
This repo seems to have been abandoned.
A maintained fork is available here
https://github.com/hagay3/skuber
Please open the issue in the new repo in order to address the issue.
Thanks,
Hagai
