### ISSUE TITLE
Ingress validation fails if an HTTPIngressPath is missing the path

### ISSUE THREAD

**Issue by cgbaker** [doriordan/skuber#38]
Per the API documentation (and my own testing), `path` is optional in an HTTPIngressPath. 
However, skuber 1.3.0 treats `skuber.ext.Ingress#Path#path` as a mandatory `String`.
I'm working on a pull request that handles missing `path` field from Kubernetes responses.

**Comment by cgbaker** [comment]
requesting review by @doriordan

**Comment by doriordan** [comment]
I'll close this issue now as the PR has been merged - thanks
