### ISSUE TITLE
Skuber should support StatefulSet extension object

### ISSUE THREAD

**Issue by hollinwilkins** [doriordan/skuber#40]
StatefulSets are very useful and the only way to perform certain tasks. Skuber should support them.

**Comment by hollinwilkins** [comment]
@doriordan I'll make a PR for this sometime today unless you have other plans for it?

**Comment by doriordan** [comment]
@hollinwilkins I agree StatefulSets need to be supported - I haven't done anything on it yet so please feel free to raise a PR...

**Comment by hollinwilkins** [comment]
Cool, I'm starting work on this now

**Comment by hollinwilkins** [comment]
@doriordan 

This is the spec code I wrote:
```
  case class Spec(replicas: Int = 1,
                  selector: Option[LabelSelector] = None,
                  serviceName: String,
                  template: Option[Pod.Template.Spec] = None,
                  volumeClaimTemplates: List[PersistentVolumeClaim])
```

Wondering if we should make the volumeClaimTemplates an Option[List] instead of just a list?

**Comment by hollinwilkins** [comment]
So I have a changeset ready, complete with unit tests and everything. I can't figure out what the REST API endpoint is though, and I don't see it in the swagger doc for the v1beta1 extension API.

**Comment by hollinwilkins** [comment]
Just created a PR for this: https://github.com/doriordan/skuber/pull/41

**Comment by doriordan** [comment]
Thanks @hollinwilkins, I've merged your PR so will close this issue now
