### ISSUE TITLE
Example usage for client.RequestContext#partiallyUpdate

### ISSUE THREAD

**Issue by cgbaker** [doriordan/skuber#45]
What is the proper usage for the `partiallyUpdate` method, which performs an HTTP `PATCH` on the passed object with the standard rendering? 

For example, the PATCH call to scale a Deployment (e.g., to 8 instances) simply involves passing the payload: 
```
{"spec": {"replicas": 8}}
```

Because most objects have a mandatory `metadata: ObjectMeta` field, this will always be constructed, rendered and passed as part of the `PATCH` request body. The minimal PATCH construction seems to be this: 
```
sk8.partiallyUpdate[Deployment](Deployment("test-depl").withReplicas(8))
```
for which the corresponding payload is: 
```
{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "test-depl",
    "namespace": "default"
  },
  "spec": {
    "replicas": 8
  }
}
```

The good news is that this, according to my manual testing against Kube 1.5.5, seems to work. I was wondering what the thoughts were on this, and whether it was worthwhile checking in some examples and/or tests to document and/or protect this.

**Comment by doriordan** [comment]
To be honestI had forgotten that the ```partiallyUpdate``` method exists...I've never tested/used it...and I'm surprised if it works as it doesn't seem to comply with any of the officially supported [Kubernetes PATCH operations](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#patch-operations)

I did have it on my todo list to properly support the above patch operations but nobody has really asked for them so it hasn't been a priority.

**Comment by cgbaker** [comment]
I tried and failed to use it for deployment scale in my application. I
didn't have time to investigate the cause, so I switched back to PUT.

**Comment by doriordan** [comment]
Closing this issue due to its age - I'll open a separate issue to request proper patch support in the long term
