### ISSUE TITLE
call k8s api-server with tls problem

### ISSUE THREAD

**Issue by feyman2016** [doriordan/skuber#52]
&ensp;&ensp;&ensp;&ensp;I've used the SKUBER_CONFIG env para to call the k8s from outside, which succeeded but not safe .Now I need to call the k8s api-server internally with the SKUBERCONFIG, according to the guide, it will read config from ~/.kube/config , which means I should have a config there or I can generate one, but it might need some modifications if I use my app in different k8s env, which means it is not that generic.
       &ensp;&ensp;&ensp;&ensp;In official go SDK, it read the config and the credential info from another path which you can see as follows:

``` func InClusterConfig() (*Config, error) {
	host, port := os.Getenv("KUBERNETES_SERVICE_HOST"), os.Getenv("KUBERNETES_SERVICE_PORT")
	if len(host) == 0 || len(port) == 0 {
		return nil, fmt.Errorf("unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined")
	}
	token, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/" + api.ServiceAccountTokenKey)
	if err != nil {
		return nil, err
	}
	tlsClientConfig := TLSClientConfig{}
	rootCAFile := "/var/run/secrets/kubernetes.io/serviceaccount/" + api.ServiceAccountRootCAKey
	if _, err := crypto.CertPoolFromFile(rootCAFile); err != nil {
		glog.Errorf("Expected to load root CA config from %s, but got err: %v", rootCAFile, err)
	} else {
		tlsClientConfig.CAFile = rootCAFile
	}

	return &Config{
		// TODO: switch to using cluster DNS.
		Host:            "https://" + net.JoinHostPort(host, port),
		BearerToken:     string(token),
		TLSClientConfig: tlsClientConfig,
	}, nil
}```

I hope I didnt make anything wrong, and can you give an example of  calling the k8s-server api with tls without specific configuration?Thanks!

**Comment by doriordan** [comment]
Can you be more precise on what you want to do?
It is possible to create a [Configuration](https://github.com/doriordan/skuber/blob/master/client/src/main/scala/skuber/api/Configuration.scala) object in your app from the various configuration details (which you could gather from environment variables, files or wherever) and pass that as the initialisation parameter to the k8s init call - though that is obviously a fair bit of code it is the most flexible method. But if your use cas eis simpler there might be something we can support "out of the box".

**Comment by feyman2016** [comment]
Thanks for your response, what I actually mean is that  it would be nice to use the SDK without knowing what happened underneath(like http or https)，and that is what you can acheive by the go SDK. 
When using the SKUBER, when I need to call the k8s api server internally through https, I need to offer the credentials, and the SKUBER by default will try to find clues from the ~/.kube/config , which is probably not exsits on the k8s cluster(of cause I can create one). If the SKUBER cannot find the right credentials , them the call to k8s api server would fail with SSL error. 
Actually I have solved this by create a kubeConfig programatically before `k8sInit`,  and specified the token or the ca.crt path as `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` (I use my app inside a pod booted by k8s), which is hint by the Go SDK. 
At first I think it's kind of more convenient when using the Go SDK, but now I think the Go SDK is more restricted ,while the Scala SDK is more flexible.
From a user's pespective, I think maybe you can put a example on the configuration README.

**Comment by doriordan** [comment]
Apologies for late response. Currently if initialising skuber using an in-memory Configuration object (as opposed to a kubeconfig file) then any certs need to be already loaded into that Configuration object, a path reference won't work as you point out  because the logic to read certs from paths is in the kubeconfig stream parsing at https://github.com/doriordan/skuber/blob/master/client/src/main/scala/skuber/api/Configuration.scala#L55
A workaround would be to create an input stream for your serialised config (e.g. in String format) and pass it to the above parser.

**Comment by doriordan** [comment]
Closing this due to its age and a reasonable workaround being available
