### ISSUE TITLE
Support for auth-providers

### ISSUE THREAD

**Issue by andrewstevenson** [doriordan/skuber#80]
Is there and support for auth-providers suchs gcp?

    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: /Users/andrew/google-cloud-sdk/bin/gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp

**Comment by doriordan** [comment]
Skuber doesn't currently directly support optional auth providers such as gcp or oidc and it isn't on the roadmap. Using a proxy (kubectl proxy probably) can work well for such cases.

**Comment by doriordan** [comment]
PR #59 (just merged) adds support for oidc authentication, but it is currently very limited - it will use a configured id-token but doesn't support refreshing when expired. More work needed to really flesh it out

**Comment by javierarrieta** [comment]
Hi, I need this and therefore I am working on it right now. I am thinking about changing `AuthInfo` to an ADT so that we know what a valid config is for every type of auth, I have a branch ready. Early feedback appreciated before following this avenue to implement gcp and OIDC this way, but this is how the ADT would look like:

```scala

   sealed trait AuthInfo

   object NoAuth extends AuthInfo {
     override def toString: String = "NoAuth"
   }

   final case class BasicAuth(userName: String, password: String) extends AuthInfo {
     override def toString: String = s"${getClass.getSimpleName}(userName=$userName,password=<redacted>)"
   }

   final case class TokenAuth(token: String) extends AuthInfo {
     override def toString: String = s"${getClass.getSimpleName}(token=<redacted>)"
   }

   final case class CertAuth(clientCertificate: PathOrData, clientKey: PathOrData, user: Option[String]) extends AuthInfo {
     override def toString: String = StringBuilder.newBuilder
       .append(getClass.getSimpleName)
       .append("(")
       .append {
         clientCertificate match {
           case Left(certPath: String) => "clientCertificate=" + certPath + " "
           case Right(_: Array[Byte]) => "clientCertificate=<PEM masked> "
         }
       }
       .append {
         clientKey match {
           case Left(certPath: String) => "clientKey=" + certPath + " "
           case Right(_: Array[Byte]) => "clientKey=<PEM masked> "
         }
       }
       .append("userName=")
       .append(user.getOrElse(""))
       .append(" )")
       .mkString
   }
```

**Comment by javierarrieta** [comment]
Pushed a PR to add gcp support and have the refresh ready to be worked on but would like feedback on the approach before starting adding more work on it

**Comment by doriordan** [comment]
Closing this issue after merging PR #121
