### ISSUE TITLE
Support for running inside K8s with the mounted service account

### ISSUE THREAD

**Issue by agemooij** [doriordan/skuber#84]
I'm writing an application with skuber that runs on K8s and creates/deploys other applications on k8s, e.g. my skuber code itself runs within k8s.

The current initialization expects a kubeconfig file setup, which is very hard to create inside a pod. I'm working on cobbling together some way of getting this to work but it's far from ideal. 

Any pod running inside of k8s will have its service account, token, and client certificate mounted as files (see [Accessing the API from a pod](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod)), which could be used by skuber to set up the connection instead of the kubeconfig. 

I think this alternative "running side k8s" initialization strategy should be supported.

References:
- [Accessing the API from a pod](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod)

**Comment by doriordan** [comment]
I have worked with Skuber use cases that are essentially the same as you describe - the solution used is a kubectl proxy running in a sidecar which is one of the options recommended in the documentation you link to above , and described in some detail [here](https://github.com/kubernetes/examples/tree/master/staging/kubectl-container/). 
This option works well in my experience - you just configure Skuber to point to the local proxy using either SKUBER_URL environment variable or an explicit Configuration object passed to the init call (with the latest version 2 release of Skuber you can really easily [create a Configuration](https://github.com/doriordan/skuber/blob/release_2.0/client/src/main/scala/skuber/api/Configuration.scala#L33) for this programmatically.  
Is this an option for your use case?

**Comment by agemooij** [comment]
The sidecar solution feels extremely heavy too me so, since we're using 2.0 I did indeed end up using a custom configuration, which I'll post below. 

If that looks interesting to you, we might want to turn it into a standard option because I would guess this is actually a common scenario. I could create a small PR if you like.

```scala
// import the typical akka stuff

import skuber._
import skuber.api._
import skuber.api.client._

object Demo extends App {
  implicit val system = ActorSystem("demo")
  implicit val materializer = ActorMaterializer()
  implicit val executionContext = system.dispatcher

  getListOfAllNamespacesUsingSkuber()
    .foreach { namespaces =>
      println(s"namespaces:\n $namespaces")
      system.terminate()
    }

  // This is just a quick inline test to prove that skuber can be configured like this
  private def getListOfAllNamespacesUsingSkuber(): Future[String] = {
    val token = FileUtils.contentsOfFile("/var/run/secrets/kubernetes.io/serviceaccount/token")
    val namespace = FileUtils.contentsOfFile("/var/run/secrets/kubernetes.io/serviceaccount/namespace")
    val k8sConfig = createK8sConfiguration(token, namespace)
    val k8s = k8sInit(k8sConfig)

    k8s.getNamespaceNames().map(_.mkString("\n"))
  }

  private def createK8sConfiguration(token: String, namespaceName: String): Configuration = {
    val cluster = Cluster(
      server = "https://kubernetes.default",
      insecureSkipTLSVerify = false,
      certificateAuthority = Some(Left("/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"))
    )

    val authInfo = AuthInfo(token = Some(token))
    val namespace = Namespace.forName(namespaceName)
    val context = Context(cluster, authInfo, namespace)

    Configuration(
      clusters = Map("default" -> cluster),
      contexts = Map("default" -> context),
      currentContext = context
    )
  }
}

object FileUtils {
  import java.nio.file._
  import java.nio.charset.StandardCharsets._

  def contentsOfFile(path: String): String = {
    new String(Files.readAllBytes(Paths.get(path)), UTF_8)
  }
}
```

**Comment by doriordan** [comment]
The configuration does look straightforward and I agree would be a good standard option to add - PR would be welcome...

**Comment by agemooij** [comment]
Noted. I'll see what I can do.

**Comment by javierarrieta** [comment]
Are you still working on this? I am going to use it in our project, could submit a PR if there is still interest

**Comment by agemooij** [comment]
@javierarrieta as so often happens, I completely forgot about this after after I got it to work for my own use case. Please feel completely free to translate the above to a PR. I'll gladly help reviewing it.

**Comment by doriordan** [comment]
#120 has now been merged so closing this issue
