### ISSUE TITLE
Support for the NetworkPolicy resource

### ISSUE THREAD

**Issue by olofwalker** [doriordan/skuber#86]
It would be very handy if Skuber could support the [NetworkPolicy resource type](https://kubernetes.io/docs/concepts/services-networking/network-policies/).

**Comment by doriordan** [comment]
Agreed, it should be straightforward to add it

**Comment by doriordan** [comment]
I propose supporting Kubernetes 1.7+ with this feature (i.e. the v1 but not the deprecated  v1beta1 version of this resource type)

**Comment by doriordan** [comment]
Added support for this feature to master per above
