### ISSUE TITLE
Missing implicit for ResourceDefinition[RoleBindingList]

### ISSUE THREAD

**Issue by olofwalker** [doriordan/skuber#95]
When trying to use the following construct to look up a Rolebinding:

```
    val roleBindingAlreadyCreated = k8s
      .listInNamespace[RoleBindingList](nameOfNamespace)
      .map(_.contains(roleBinding.metadata.name))
```

I got a compile error of a missing implicit, that I think should look something like this in Rolebinding.scala

`implicit val roleListDef = new ResourceDefinition[RoleBindingList] { def spec = specification }`

**Comment by doriordan** [comment]
Closing as fixed by #96
